### ISSUE TITLE
Pytest is failing because 'app' is undefined in delegate.py

### ISSUE THREAD

**Issue by cclauss** [infogami/infogami#4]
In __app.py__ it is defined like this:
https://github.com/infogami/infogami/blob/master/infogami/utils/app.py#L10-L11

In __server.py__ is is defined like this:
https://github.com/infogami/infogami/blob/master/infogami/infobase/server.py#L26-L50

But __delegate.py__ it is not defined at all:
https://github.com/infogami/infogami/blob/master/infogami/utils/delegate.py#L96-L99

Leading to: https://travis-ci.org/internetarchive/infogami/jobs/470491332#L5164

**Comment by tfmorris** [comment]
Here's a permalinked version of the PR to enable embedded quoting:

> In app.py it is defined like this:
https://github.com/infogami/infogami/blob/b0bb38686ad79454dd60ed919f903bd282b3de78/infogami/utils/app.py#L10-L11
>
>In server.py is is defined like this:
https://github.com/infogami/infogami/blob/52fda4a20647886bb15e91cb91d8f17ac05d07c4/infogami/infobase/server.py#L26-L50
>
>But delegate.py it is not defined at all:
https://github.com/infogami/infogami/blob/229a86074dacb6f5b1220f9635068fd88e7fa1b9/infogami/utils/delegate.py#L96-L99
>
>Leading to: https://travis-ci.org/internetarchive/infogami/jobs/470491332#L5164
