### ISSUE TITLE
Remove OrderedDict and DefaultDict from infogami/utils/storage.py 

### ISSUE THREAD

**Issue by cclauss** [infogami/infogami#5]
https://github.com/infogami/infogami/blob/master/infogami/utils/storage.py#L9 contains redefinitions of __OrderedDict__ and __DefaultDict__ which are now in the Standard Library.

**Comment by tfmorris** [comment]
We should decide whether we're going to:

1. Deprecate the local definitions and wrap the standard Python implementations
1. Declare them obsolete and tell people to use the standard Python declarations

The second is less work and fine with me, considering that they're drop-in replacements and anyone using the implementation will already be dealing with source changes for the Python 3 upgrade anyway.

**Comment by cclauss** [comment]
My vote would be 2.

**Comment by cclauss** [comment]
Closing as fixed on internetarchive/infogami
